#! /bin/bash
#
# This script resets the choria config for a Namespace

PARENT="$(cd $(dirname "$0") && pwd)"
: "${NAMESPACE:=jeff-holos}"
export NAMESPACE

set -xeuo pipefail

KUBECONFIG=$HOME/.holos/kubeconfig.provisioner kubectl delete secret -n jeff-holos choria-agents choria-broker choria-provisioner choria-issuer

"${PARENT}/init-choria-provisioner-creds"

stamp="$(date)"

kubectl -n $NAMESPACE annotate externalsecret choria-broker secret.holos.run/refresh="$stamp" --overwrite
kubectl -n $NAMESPACE annotate externalsecret choria-provisioner secret.holos.run/refresh="$stamp" --overwrite

kubectl -n $NAMESPACE wait --for='jsonpath={.status.conditions[?(@.type=="Ready")].status}=True' externalsecret choria-provisioner choria-broker

kubectl -n $NAMESPACE rollout restart statefulset choria-broker
kubectl -n $NAMESPACE rollout restart deployment choria-provisioner
