// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/gofrs/uuid"
	"github.com/holos-run/holos/internal/ent/organization"
	entplatform "github.com/holos-run/holos/internal/ent/platform"
	"github.com/holos-run/holos/internal/ent/schema"
	"github.com/holos-run/holos/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationMixinFields1 := organizationMixin[1].Fields()
	_ = organizationMixinFields1
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields1[0].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields1[1].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[0].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationMixinFields0[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	entplatformMixin := schema.Platform{}.Mixin()
	entplatformMixinFields0 := entplatformMixin[0].Fields()
	_ = entplatformMixinFields0
	entplatformMixinFields1 := entplatformMixin[1].Fields()
	_ = entplatformMixinFields1
	entplatformFields := schema.Platform{}.Fields()
	_ = entplatformFields
	// entplatformDescCreatedAt is the schema descriptor for created_at field.
	entplatformDescCreatedAt := entplatformMixinFields1[0].Descriptor()
	// entplatform.DefaultCreatedAt holds the default value on creation for the created_at field.
	entplatform.DefaultCreatedAt = entplatformDescCreatedAt.Default.(func() time.Time)
	// entplatformDescUpdatedAt is the schema descriptor for updated_at field.
	entplatformDescUpdatedAt := entplatformMixinFields1[1].Descriptor()
	// entplatform.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entplatform.DefaultUpdatedAt = entplatformDescUpdatedAt.Default.(func() time.Time)
	// entplatform.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entplatform.UpdateDefaultUpdatedAt = entplatformDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entplatformDescName is the schema descriptor for name field.
	entplatformDescName := entplatformFields[1].Descriptor()
	// entplatform.NameValidator is a validator for the "name" field. It is called by the builders before save.
	entplatform.NameValidator = entplatformDescName.Validators[0].(func(string) error)
	// entplatformDescID is the schema descriptor for id field.
	entplatformDescID := entplatformMixinFields0[0].Descriptor()
	// entplatform.DefaultID holds the default value on creation for the id field.
	entplatform.DefaultID = entplatformDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
