// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/gofrs/uuid"
	"github.com/holos-run/holos/internal/ent/schema"
	"github.com/holos-run/holos/internal/ent/user"
	"github.com/holos-run/holos/internal/ent/useridentity"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[1].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	useridentityMixin := schema.UserIdentity{}.Mixin()
	useridentityMixinFields0 := useridentityMixin[0].Fields()
	_ = useridentityMixinFields0
	useridentityMixinFields1 := useridentityMixin[1].Fields()
	_ = useridentityMixinFields1
	useridentityFields := schema.UserIdentity{}.Fields()
	_ = useridentityFields
	// useridentityDescCreatedAt is the schema descriptor for created_at field.
	useridentityDescCreatedAt := useridentityMixinFields1[0].Descriptor()
	// useridentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	useridentity.DefaultCreatedAt = useridentityDescCreatedAt.Default.(func() time.Time)
	// useridentityDescUpdatedAt is the schema descriptor for updated_at field.
	useridentityDescUpdatedAt := useridentityMixinFields1[1].Descriptor()
	// useridentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useridentity.DefaultUpdatedAt = useridentityDescUpdatedAt.Default.(func() time.Time)
	// useridentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useridentity.UpdateDefaultUpdatedAt = useridentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// useridentityDescIss is the schema descriptor for iss field.
	useridentityDescIss := useridentityFields[0].Descriptor()
	// useridentity.IssValidator is a validator for the "iss" field. It is called by the builders before save.
	useridentity.IssValidator = useridentityDescIss.Validators[0].(func(string) error)
	// useridentityDescSub is the schema descriptor for sub field.
	useridentityDescSub := useridentityFields[1].Descriptor()
	// useridentity.SubValidator is a validator for the "sub" field. It is called by the builders before save.
	useridentity.SubValidator = useridentityDescSub.Validators[0].(func(string) error)
	// useridentityDescEmail is the schema descriptor for email field.
	useridentityDescEmail := useridentityFields[2].Descriptor()
	// useridentity.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	useridentity.EmailValidator = useridentityDescEmail.Validators[0].(func(string) error)
	// useridentityDescEmailVerified is the schema descriptor for email_verified field.
	useridentityDescEmailVerified := useridentityFields[3].Descriptor()
	// useridentity.DefaultEmailVerified holds the default value on creation for the email_verified field.
	useridentity.DefaultEmailVerified = useridentityDescEmailVerified.Default.(bool)
	// useridentityDescID is the schema descriptor for id field.
	useridentityDescID := useridentityMixinFields0[0].Descriptor()
	// useridentity.DefaultID holds the default value on creation for the id field.
	useridentity.DefaultID = useridentityDescID.Default.(func() uuid.UUID)
}
