// Code generated by ent, DO NOT EDIT.

package platform

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gofrs/uuid"
	"github.com/holos-run/holos/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldOrgID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldDisplayName, v))
}

// CreatorID applies equality check predicate on the "creator_id" field. It's identical to CreatorIDEQ.
func CreatorID(v uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldCreatorID, v))
}

// ConfigForm applies equality check predicate on the "config_form" field. It's identical to ConfigFormEQ.
func ConfigForm(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldConfigForm, v))
}

// ConfigValues applies equality check predicate on the "config_values" field. It's identical to ConfigValuesEQ.
func ConfigValues(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldConfigValues, v))
}

// ConfigCue applies equality check predicate on the "config_cue" field. It's identical to ConfigCueEQ.
func ConfigCue(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldConfigCue, v))
}

// ConfigDefinition applies equality check predicate on the "config_definition" field. It's identical to ConfigDefinitionEQ.
func ConfigDefinition(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldConfigDefinition, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldOrgID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Platform {
	return predicate.Platform(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Platform {
	return predicate.Platform(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Platform {
	return predicate.Platform(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Platform {
	return predicate.Platform(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Platform {
	return predicate.Platform(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Platform {
	return predicate.Platform(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Platform {
	return predicate.Platform(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Platform {
	return predicate.Platform(sql.FieldContainsFold(FieldDisplayName, v))
}

// CreatorIDEQ applies the EQ predicate on the "creator_id" field.
func CreatorIDEQ(v uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldCreatorID, v))
}

// CreatorIDNEQ applies the NEQ predicate on the "creator_id" field.
func CreatorIDNEQ(v uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldCreatorID, v))
}

// CreatorIDIn applies the In predicate on the "creator_id" field.
func CreatorIDIn(vs ...uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldCreatorID, vs...))
}

// CreatorIDNotIn applies the NotIn predicate on the "creator_id" field.
func CreatorIDNotIn(vs ...uuid.UUID) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldCreatorID, vs...))
}

// ConfigFormEQ applies the EQ predicate on the "config_form" field.
func ConfigFormEQ(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldConfigForm, v))
}

// ConfigFormNEQ applies the NEQ predicate on the "config_form" field.
func ConfigFormNEQ(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldConfigForm, v))
}

// ConfigFormIn applies the In predicate on the "config_form" field.
func ConfigFormIn(vs ...[]byte) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldConfigForm, vs...))
}

// ConfigFormNotIn applies the NotIn predicate on the "config_form" field.
func ConfigFormNotIn(vs ...[]byte) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldConfigForm, vs...))
}

// ConfigFormGT applies the GT predicate on the "config_form" field.
func ConfigFormGT(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldConfigForm, v))
}

// ConfigFormGTE applies the GTE predicate on the "config_form" field.
func ConfigFormGTE(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldConfigForm, v))
}

// ConfigFormLT applies the LT predicate on the "config_form" field.
func ConfigFormLT(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldConfigForm, v))
}

// ConfigFormLTE applies the LTE predicate on the "config_form" field.
func ConfigFormLTE(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldConfigForm, v))
}

// ConfigFormIsNil applies the IsNil predicate on the "config_form" field.
func ConfigFormIsNil() predicate.Platform {
	return predicate.Platform(sql.FieldIsNull(FieldConfigForm))
}

// ConfigFormNotNil applies the NotNil predicate on the "config_form" field.
func ConfigFormNotNil() predicate.Platform {
	return predicate.Platform(sql.FieldNotNull(FieldConfigForm))
}

// ConfigValuesEQ applies the EQ predicate on the "config_values" field.
func ConfigValuesEQ(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldConfigValues, v))
}

// ConfigValuesNEQ applies the NEQ predicate on the "config_values" field.
func ConfigValuesNEQ(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldConfigValues, v))
}

// ConfigValuesIn applies the In predicate on the "config_values" field.
func ConfigValuesIn(vs ...[]byte) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldConfigValues, vs...))
}

// ConfigValuesNotIn applies the NotIn predicate on the "config_values" field.
func ConfigValuesNotIn(vs ...[]byte) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldConfigValues, vs...))
}

// ConfigValuesGT applies the GT predicate on the "config_values" field.
func ConfigValuesGT(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldConfigValues, v))
}

// ConfigValuesGTE applies the GTE predicate on the "config_values" field.
func ConfigValuesGTE(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldConfigValues, v))
}

// ConfigValuesLT applies the LT predicate on the "config_values" field.
func ConfigValuesLT(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldConfigValues, v))
}

// ConfigValuesLTE applies the LTE predicate on the "config_values" field.
func ConfigValuesLTE(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldConfigValues, v))
}

// ConfigValuesIsNil applies the IsNil predicate on the "config_values" field.
func ConfigValuesIsNil() predicate.Platform {
	return predicate.Platform(sql.FieldIsNull(FieldConfigValues))
}

// ConfigValuesNotNil applies the NotNil predicate on the "config_values" field.
func ConfigValuesNotNil() predicate.Platform {
	return predicate.Platform(sql.FieldNotNull(FieldConfigValues))
}

// ConfigCueEQ applies the EQ predicate on the "config_cue" field.
func ConfigCueEQ(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldConfigCue, v))
}

// ConfigCueNEQ applies the NEQ predicate on the "config_cue" field.
func ConfigCueNEQ(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldConfigCue, v))
}

// ConfigCueIn applies the In predicate on the "config_cue" field.
func ConfigCueIn(vs ...[]byte) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldConfigCue, vs...))
}

// ConfigCueNotIn applies the NotIn predicate on the "config_cue" field.
func ConfigCueNotIn(vs ...[]byte) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldConfigCue, vs...))
}

// ConfigCueGT applies the GT predicate on the "config_cue" field.
func ConfigCueGT(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldConfigCue, v))
}

// ConfigCueGTE applies the GTE predicate on the "config_cue" field.
func ConfigCueGTE(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldConfigCue, v))
}

// ConfigCueLT applies the LT predicate on the "config_cue" field.
func ConfigCueLT(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldConfigCue, v))
}

// ConfigCueLTE applies the LTE predicate on the "config_cue" field.
func ConfigCueLTE(v []byte) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldConfigCue, v))
}

// ConfigCueIsNil applies the IsNil predicate on the "config_cue" field.
func ConfigCueIsNil() predicate.Platform {
	return predicate.Platform(sql.FieldIsNull(FieldConfigCue))
}

// ConfigCueNotNil applies the NotNil predicate on the "config_cue" field.
func ConfigCueNotNil() predicate.Platform {
	return predicate.Platform(sql.FieldNotNull(FieldConfigCue))
}

// ConfigDefinitionEQ applies the EQ predicate on the "config_definition" field.
func ConfigDefinitionEQ(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEQ(FieldConfigDefinition, v))
}

// ConfigDefinitionNEQ applies the NEQ predicate on the "config_definition" field.
func ConfigDefinitionNEQ(v string) predicate.Platform {
	return predicate.Platform(sql.FieldNEQ(FieldConfigDefinition, v))
}

// ConfigDefinitionIn applies the In predicate on the "config_definition" field.
func ConfigDefinitionIn(vs ...string) predicate.Platform {
	return predicate.Platform(sql.FieldIn(FieldConfigDefinition, vs...))
}

// ConfigDefinitionNotIn applies the NotIn predicate on the "config_definition" field.
func ConfigDefinitionNotIn(vs ...string) predicate.Platform {
	return predicate.Platform(sql.FieldNotIn(FieldConfigDefinition, vs...))
}

// ConfigDefinitionGT applies the GT predicate on the "config_definition" field.
func ConfigDefinitionGT(v string) predicate.Platform {
	return predicate.Platform(sql.FieldGT(FieldConfigDefinition, v))
}

// ConfigDefinitionGTE applies the GTE predicate on the "config_definition" field.
func ConfigDefinitionGTE(v string) predicate.Platform {
	return predicate.Platform(sql.FieldGTE(FieldConfigDefinition, v))
}

// ConfigDefinitionLT applies the LT predicate on the "config_definition" field.
func ConfigDefinitionLT(v string) predicate.Platform {
	return predicate.Platform(sql.FieldLT(FieldConfigDefinition, v))
}

// ConfigDefinitionLTE applies the LTE predicate on the "config_definition" field.
func ConfigDefinitionLTE(v string) predicate.Platform {
	return predicate.Platform(sql.FieldLTE(FieldConfigDefinition, v))
}

// ConfigDefinitionContains applies the Contains predicate on the "config_definition" field.
func ConfigDefinitionContains(v string) predicate.Platform {
	return predicate.Platform(sql.FieldContains(FieldConfigDefinition, v))
}

// ConfigDefinitionHasPrefix applies the HasPrefix predicate on the "config_definition" field.
func ConfigDefinitionHasPrefix(v string) predicate.Platform {
	return predicate.Platform(sql.FieldHasPrefix(FieldConfigDefinition, v))
}

// ConfigDefinitionHasSuffix applies the HasSuffix predicate on the "config_definition" field.
func ConfigDefinitionHasSuffix(v string) predicate.Platform {
	return predicate.Platform(sql.FieldHasSuffix(FieldConfigDefinition, v))
}

// ConfigDefinitionIsNil applies the IsNil predicate on the "config_definition" field.
func ConfigDefinitionIsNil() predicate.Platform {
	return predicate.Platform(sql.FieldIsNull(FieldConfigDefinition))
}

// ConfigDefinitionNotNil applies the NotNil predicate on the "config_definition" field.
func ConfigDefinitionNotNil() predicate.Platform {
	return predicate.Platform(sql.FieldNotNull(FieldConfigDefinition))
}

// ConfigDefinitionEqualFold applies the EqualFold predicate on the "config_definition" field.
func ConfigDefinitionEqualFold(v string) predicate.Platform {
	return predicate.Platform(sql.FieldEqualFold(FieldConfigDefinition, v))
}

// ConfigDefinitionContainsFold applies the ContainsFold predicate on the "config_definition" field.
func ConfigDefinitionContainsFold(v string) predicate.Platform {
	return predicate.Platform(sql.FieldContainsFold(FieldConfigDefinition, v))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.Platform {
	return predicate.Platform(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.Platform {
	return predicate.Platform(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.Platform {
	return predicate.Platform(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.Platform {
	return predicate.Platform(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Platform) predicate.Platform {
	return predicate.Platform(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Platform) predicate.Platform {
	return predicate.Platform(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Platform) predicate.Platform {
	return predicate.Platform(sql.NotPredicates(p))
}
