import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  doc: [
    'introduction',
    'technical-overview',
    {
      label: 'Getting Started',
      type: 'category',
      collapsed: true,
      link: { type: 'doc', id: 'start' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'start',
        },
      ],
    },
    {
      label: 'Guides',
      type: 'category',
      collapsed: false,
      link: { type: 'doc', id: 'guides' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      label: 'API Reference',
      type: 'category',
      collapsed: true,
      link: { type: 'doc', id: 'api' },
      items: [
        {
          label: 'Author API',
          type: 'category',
          link: { type: 'doc', id: 'api/author' },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/author',
            },
          ]
        },
        {
          label: 'Core API',
          type: 'category',
          link: { type: 'doc', id: 'api/core' },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/core',
            },
          ]
        },
      ]
    },
  ],
};

export default sidebars;
