#! /bin/bash
#
set -euo pipefail

TOPLEVEL="$(cd $(dirname "$0") && git rev-parse --show-toplevel)"
cd "${TOPLEVEL}"

if ! [[ -f ./doc/website/node_modules/.bin/cspell ]]; then
  (cd doc/website && npm install)
fi

./doc/website/node_modules/.bin/cspell ./doc/md/**/*.{md,mdx,markdown} ./doc/md/*.{md,mdx,markdown}
