#! /bin/bash
#

set -euo pipefail

export PROJECT_ID="$(gcloud config get-value project)"
export PROJECT_NUMBER="$(gcloud projects describe $PROJECT_ID --format='value(projectNumber)')"

envsubst < rolebinding.template.yaml > rolebinding.yaml
echo "Apply rolebinding.yaml to seed cluster"
