#! /bin/bash

set -euo pipefail
TOPLEVEL="$(cd $(dirname "$0") && git rev-parse --show-toplevel)"

host="jeff.app.dev.k2.holos.run:443"

read -p "Reset all data in $host? " choice
case "$choice" in
  y|Y) echo "proceeding...";;
  *) exit 1;;
esac


grpcurl -H "x-oidc-id-token: $(holos token)" $host holos.v1alpha1.SystemService.DropTables
grpcurl -H "x-oidc-id-token: $(holos token)" $host holos.v1alpha1.SystemService.SeedDatabase
