#! /bin/bash
#
set -xeuo pipefail

cd "$HOME"

gcloud config set disable_usage_reporting true
gcloud auth login --cred-file $GOOGLE_APPLICATION_CREDENTIALS

export KUBECONFIG="${HOME}/kubeconfig.seed"

# Log into k8s.
gcloud container clusters get-credentials holos --region=us-central1

# Check access.
kubectl version --output=yaml

sleep 3600
