---
name: Spelling
"on":
  push:
    branches:
      - main
      - test
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./hack/cspell
